### ISSUE TITLE
was ist theme-custom.css?

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS22#12]
@DLND8, ist das von dir? Was bewirkt diese Einstellung?

https://github.com/ResearchMethods-ZHAW/HS22/blob/f2953ef2b55b203e2b326200eba749824629a1c1/theme-custom.scss#L1-L2

**Comment by DLND8** [comment]
@ratnanil Ja das habe ich hinzugefügt um die Sidebar ein wenig zu vergrössern.
