### ISSUE TITLE
Error with new piping operator |>

### ISSUE THREAD

**Issue by DLND8** [ResearchMethods-ZHAW/HS22#13]
Somehow `|>` does not work with . in the second operation.

- Doesn't work: `wind250m <- wind25m |> aggregate(.,fact = 10)`
   ```
  Fehler in .makeTextFun(fun) : Objekt '.' nicht gefunden
  Ruft auf: .main ... eval -> aggregate -> aggregate -> .local -> .makeTextFun
  ```
- Works: `wind250m <- wind25m %>% aggregate(.,fact = 10)`

**Comment by ratnanil** [comment]
just omit the "`.`"

```r
wind250m <- wind25m |> aggregate(fact = 10)
```

**Comment by DLND8** [comment]
InfoVis, PrePro and RaumAn are now using only |>
