### ISSUE TITLE
untracked data/ folder

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS22#14]
I changed something in the file metadata.csv, @DLND8 you now need download the file from moodle and replace the old metadata.csv. I'm not too happy about his manual approach, but don't have an alternative suggestion.

**Comment by ratnanil** [comment]
Since hoce does not have datasets that we use in InfoVis, Demo 1 throws an error after hoce pushed his changes:

```
Error: 'data/temperature_SHA_ZER.csv' does not exist in current working directory ('C:/Users/hoce/OneDrive - ZHAW/Dokumente/02a_MSc/Research-Methods_Fallstudie/HS22').
```

**Comment by DLND8** [comment]
We will use a submodule of the datasets repo which will be private
