### ISSUE TITLE
merge all gpkg files into one

### ISSUE THREAD

**Issue by ratnanil** [ResearchMethods-ZHAW/HS22#15]
It would be much easier and more userfriendly if all gpkg files were merged into one

https://researchmethods-zhaw.github.io/HS22/rauman/Rauman5_Uebung_mce.html#tbl-data

**Comment by DLND8** [comment]
done with https://github.com/ResearchMethods-ZHAW/HS22/commit/66bcf8f888a12015f35337435146467fb026df26
