### ISSUE TITLE
Error in file(con, "r") : cannot open the connection

### ISSUE THREAD

**Issue by GAEgeler** [ResearchMethods-ZHAW/HS22#17]
I'm having problem to render some of the qmd files. do you have any suggestions?

cheers

**Comment by ratnanil** [comment]
I need more context on this! Does this happens when you press the *Render* button on the individual .qmd? If so, try to work with the command `quarto.cmd preview` in the terminal. Can you call Dominik if this does not work?

Cheers,

Nils

**Comment by DLND8** [comment]
This should be fixed now as we do not use purl anymore

I general please use `quarto render folder` to render the pages.
