### ISSUE TITLE
message=FALSE

### ISSUE THREAD

**Issue by hochad** [ResearchMethods-ZHAW/HS22#6]
@DLND8: Die Einstellungen für "code chunks" werden neu global gemacht, oder? Ich wäre dafür, dass wir _message=FALSE_ setzen und damit die Meldungen, dass die Bibliotheken geladen wurden usw. unterdrücken. Ok?

**Comment by DLND8** [comment]
@hochad Also global nicht aber du kannst es einfach pro File definieren e.g.:

````
```{r}
    #| include: false
    #| purl: false
    knitr::opts_chunk$set(message = FALSE)
```
````

**Comment by ratnanil** [comment]
Doch, wir können die Einstellungen für Code Chunks global ändern, und zwar in `_quarto.yml` im Teil `execute`, also hier:

https://github.com/ResearchMethods-ZHAW/HS22/blob/a3d8d83f6d246678544788f1dab36b3bfddff552/_quarto.yml#L16-L18

Wir können also Messages und auch Warnings ausschalten, in dem wir `_quarto.yml` folgendermassen ergänzen:

```
 execute: 
   freeze: true 
   error: true 
   message: false
   warning: false
```

siehe https://quarto.org/docs/reference/cells/cells-knitr.html#cell-output

**Comment by hochad** [comment]
danke! ich habe das angepasst.
