### ISSUE TITLE
interaktive Karte

### ISSUE THREAD

**Issue by hochad** [ResearchMethods-ZHAW/HS22#7]
@DLND8: im File _fallstudie_s/2_Felderhebung.qmd_ plotte ich mit leaflet eine interaktive Karte, welche bei mir lokal gerendert wird. Der build in _Actions_ ist erfolgreich, doch die Karte wird auf der Webseite nicht angezeigt.

Hast du eine Idee, wo das Problem liegen könnte. Kann quarto interaktive Elemente darstellen?

**Comment by DLND8** [comment]
Ich sehe das du ```` ```{r results="hide"} ```` machst. Eventuell ist es wegen dem.

**Comment by hochad** [comment]
Ahh, vielen Dank. Wenn es nur immer so einfach wäre. :)
